App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: [ 'create' ]
    latitude:
      - NotBlank:
          groups: [ 'create' ]
      - Range:
          min: -90
          max: 90
          groups: [ 'create' ]
    longitude:
      - NotBlank:
          groups: [ 'create' ]
      - Range:
          min: -180
          max: 180
          groups: [ 'create' ]